version: "3.9"
services:
  django:
    env_file: .env.example
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    command: "ci"
    volumes:
      - .:/app
  postgres:
    image: "postgres:latest"
    restart: on-failure
    env_file: .env.example
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:latest"
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  meilisearch:
    image: "getmeili/meilisearch:latest"
    restart: on-failure
    ports:
      - "7700:7700"
    env_file: .env.example
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
